version: '3'

services:
  label_extractor:
    build: .
    image: gbifnorway/label-extractor:latest
    env_file:
      - .env
    volumes:
      - ./code:/srv/code
      - ./secrets:/srv/secrets
    #command: tail -f /dev/null
    entrypoint: /bin/bash
    stdin_open: true
    tty: true